### ISSUE TITLE
リクエストしたユーザーの名前表示

### ISSUE THREAD

**Issue by komatti365** [nucosen/requester-bot#21]
**想定される状況・問題**
視聴者視点（特にDiscordを使用していない人)、リクエストか否かが不透明で、今流れている動画がリクエストされたものか、あるいはランダムに選曲された動画なのかもわからない。

**提案したい解決案・改善策**
Discordのbotでリクエストした時にDiscordのユーザー名を取得し、リクエストした人の名前を表示する

**その他の解決方法・プランB**
リクエストした動画の時のみにリクエストであることを通知する

**補遺**
ユーザー名を取得するとき、トラブルを避けるためにユーザー名を取得していることを規約などで提示する必要あり

**Comment by sitting-cat** [comment]
リクエストに対してリプライ形式で返信しているため一応対応済みとします
